### PR TITLE
Moved the bundleIDsToBlock for configuration support.

### PR DESCRIPTION
**Pull request by WardsParadox**
Warning, first foray into ObjC writing, so 🤞🏻 it works off of my machine lol

### CODE REVIEW

**Comment by WardsParadox** [comment]
Also looks like XCode stripped some blank lines,sorry for the spam in that regards

**Comment by hjuutilainen** [comment]
Thanks for this. I was expecting that specifying the identifiers through configuration would come up sooner or later. My original thinking was that I'd really like to keep this project just for blocking Big Sur (hence the bigsurblocker name) and possibly create a more advanced tool in the future based on things learned from this project. At the same time I also acknowledge the need for specifying additional bundle identifiers.

I gave this a lot of though and I'm going to merge this since it has been requested a lot.

**Comment by WardsParadox** [comment]
Awesome! I totally get both sides of the thought piece. Can’t wait to see
that tool :)

**Comment by hjuutilainen** [comment]
This is now included in the latest release! Thanks again

**Pull request merged**
